<a href="https://colab.research.google.com/github/marschenone/Proyecto-Final-Schenone/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import os

os.chdir('..')
!ls

bin			    datalab  lib     media		       proc	   sbin  tools
boot			    dev      lib32   mnt		       python-apt  srv	 usr
content			    etc      lib64   NGC-DL-CONTAINER-LICENSE  root	   sys	 var
cuda-keyring_1.0-1_all.deb  home     libx32  opt		       run	   tmp

In [5]:
# Conectar Drive a Colab
from google.colab import drive
import os

# Montar drive
drive.mount("/content/drive/")
# Cambiar directorio
os.chdir('/content/drive/MyDrive/Colab Notebooks/Data/')

Mounted at /content/drive/

In [7]:
df_delitos = pd.read_csv('snic-robos-provincias-series.csv')

In [8]:
df_delitos.describe()

,indice_tiempo,robos_hechos_buenos_aires,robos_hechos_caba,robos_hechos_catamarca,robos_hechos_chaco,robos_hechos_chubut,robos_hechos_cordoba,robos_hechos_corrientes,robos_hechos_entre_rios,robos_hechos_formosa,...,robos_tasa_neuquen,robos_tasa_rio_negro,robos_tasa_salta,robos_tasa_san_juan,robos_tasa_san_luis,robos_tasa_santa_cruz,robos_tasa_santa_fe,robos_tasa_sgo_estero,robos_tasa_tierra_fuego,robos_tasa_tucuman
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,...,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,2011.500000,97568.227273,74683.090909,4518.272727,7388.954545,4760.818182,54179.636364,7238.818182,7327.454545,2533.227273,...,2045.377291,1162.968180,1125.413635,1097.481819,653.413634,898.709092,1300.800000,525.195455,611.372730,799.113641
std,6.493587,27085.972676,11782.383347,1460.642526,1956.734196,724.271498,8215.866088,1499.044192,1096.822238,742.002113,...,223.252398,247.601995,311.279493,129.597470,181.688784,173.596973,179.389999,245.450306,160.713416,284.472010
min,2001.000000,58863.000000,40178.000000,2527.000000,4433.000000,2971.000000,42771.000000,4821.000000,5712.000000,1593.000000,...,1672.500000,744.500000,454.799990,939.000000,353.700010,562.200010,972.299990,138.500000,306.100010,477.000000
25%,2006.250000,80185.000000,72983.500000,3441.250000,6375.750000,4488.500000,47132.500000,6030.250000,6601.250000,1955.750000,...,1931.100000,979.175007,1063.250000,1033.075000,472.649990,802.649995,1164.300000,378.599995,552.150008,589.825010
50%,2011.500000,94719.000000,75991.000000,4113.500000,7072.500000,4840.000000,52529.000000,7104.500000,6971.500000,2285.000000,...,2015.350000,1154.450000,1175.950000,1065.550000,675.899995,892.799990,1264.300000,476.850010,641.899995,637.550015
75%,2016.750000,112744.000000,83027.750000,5733.250000,8182.500000,5166.000000,61933.500000,8060.000000,7634.250000,3239.750000,...,2159.225100,1290.200000,1347.975000,1171.200000,805.349980,1004.999995,1465.675000,634.425003,699.199985,1038.025000
max,2022.000000,155512.000000,91763.000000,7466.000000,12822.000000,6296.000000,67288.000000,10987.000000,10091.000000,4120.000000,...,2493.100100,1727.300000,1524.800000,1487.200000,955.400020,1236.100000,1569.000000,1023.500000,899.500000,1353.800000

In [9]:
df_delitos.head()

,indice_tiempo,robos_hechos_buenos_aires,robos_hechos_caba,robos_hechos_catamarca,robos_hechos_chaco,robos_hechos_chubut,robos_hechos_cordoba,robos_hechos_corrientes,robos_hechos_entre_rios,robos_hechos_formosa,...,robos_tasa_neuquen,robos_tasa_rio_negro,robos_tasa_salta,robos_tasa_san_juan,robos_tasa_san_luis,robos_tasa_santa_cruz,robos_tasa_santa_fe,robos_tasa_sgo_estero,robos_tasa_tierra_fuego,robos_tasa_tucuman
0,2001,118351,72868,2527,11163,2971,43168,9168,6347,2207,...,1820.5,1122.80000,454.79999,1147.5,662.09998,892.59998,972.29999,378.39999,634.20001,510.00000
1,2002,153518,75283,3667,12822,3772,57319,10987,8357,2650,...,2048.0,1325.20000,572.29999,1487.2,808.09998,1174.40000,1128.00000,498.60001,813.70001,676.90002
2,2003,131978,76618,3437,9231,5060,54035,9836,8251,2278,...,2042.4,1094.60000,520.00000,1303.3,955.40002,1236.10000,1088.10000,439.50000,768.70001,595.59998
3,2004,97113,74054,3182,8565,4773,48172,8131,7643,1948,...,1988.8,944.79999,704.79999,1239.1,831.00000,1057.40000,1063.60000,574.79999,706.59998,587.90002
4,2005,64252,74773,2968,8052,4475,44656,7118,6954,1593,...,1920.6,862.50000,1063.20000,1066.3,660.29999,957.50000,1235.80000,455.10001,651.00000,647.70001

In [10]:
df_delitos.columns

Index(['indice_tiempo', 'robos_hechos_buenos_aires', 'robos_hechos_caba',
       'robos_hechos_catamarca', 'robos_hechos_chaco', 'robos_hechos_chubut',
       'robos_hechos_cordoba', 'robos_hechos_corrientes',
       'robos_hechos_entre_rios', 'robos_hechos_formosa', 'robos_hechos_jujuy',
       'robos_hechos_la_pampa', 'robos_hechos_la_rioja',
       'robos_hechos_mendoza', 'robos_hechos_misiones', 'robos_hechos_neuquen',
       'robos_hechos_rio_negro', 'robos_hechos_salta', 'robos_hechos_san_juan',
       'robos_hechos_san_luis', 'robos_hechos_santa_cruz',
       'robos_hechos_santa_fe', 'robos_hechos_sgo_estero',
       'robos_hechos_tierra_fuego', 'robos_hechos_tucuman',
       'robos_tasa_buenos_aires', 'robos_tasa_caba', 'robos_tasa_catamarca',
       'robos_tasa_chaco', 'robos_tasa_chubut', 'robos_tasa_cordoba',
       'robos_tasa_corrientes', 'robos_tasa_entre_rios', 'robos_tasa_formosa',
       'robos_tasa_jujuy', 'robos_tasa_la_pampa', 'robos_tasa_la_rioja',
       'robos_tasa_mendoza', 'robos_tasa_misiones', 'robos_tasa_neuquen',
       'robos_tasa_rio_negro', 'robos_tasa_salta', 'robos_tasa_san_juan',
       'robos_tasa_san_luis', 'robos_tasa_santa_cruz', 'robos_tasa_santa_fe',
       'robos_tasa_sgo_estero', 'robos_tasa_tierra_fuego',
       'robos_tasa_tucuman'],
      dtype='object')

In [11]:
df_delitos.shape

(22, 49)

In [12]:
df_delitos.info

<bound method DataFrame.info of     indice_tiempo  robos_hechos_buenos_aires  robos_hechos_caba  \
0            2001                     118351              72868
1            2002                     153518              75283
2            2003                     131978              76618
3            2004                      97113              74054
4            2005                      64252              74773
5            2006                      58863              81587
6            2007                      59560              86851
7            2008                      77413              91763
8            2009                      63145              85782
9            2010                      71299              84310
10           2011                      88501              83761
11           2012                      94059              83508
12           2013                      95379              76559
13           2014                      99744              80914
14           2015                      91761              67577
15           2016                      91522              76250
16           2017                      92512              73330
17           2018                     105185              75732
18           2019                     155512              67415
19           2020                     115916              40178
20           2021                     115029              50880
21           2022                     105889              63035

    robos_hechos_catamarca  robos_hechos_chaco  robos_hechos_chubut  \
0                     2527               11163                 2971
1                     3667               12822                 3772
2                     3437                9231                 5060
3                     3182                8565                 4773
4                     2968                8052                 4475
5                     3029                7816                 4529
6                     3455                7113                 5073
7                     3519                7654                 4632
8                     3219                7032                 5458
9                     4710                6799                 5346
10                    3879                5890                 4841
11                    5254                7258                 4587
12                    6196                8226                 5197
13                    7169                8503                 6296
14                    6265                6337                 5564
15                    7466                6586                 5390
16                    6161                6213                 4958
17                    5893                6760                 4839
18                    5149                6492                 4918
19                    3454                4841                 3615
20                    4348                4771                 4023
21                    4455                4433                 4421

    robos_hechos_cordoba  robos_hechos_corrientes  robos_hechos_entre_rios  \
0                  43168                     9168                     6347
1                  57319                    10987                     8357
2                  54035                     9836                     8251
3                  48172                     8131                     7643
4                  44656                     7118                     6954
5                  44250                     7489                     6557
6                  46786                     7091                     6734
7                  52008                     7684                     6948
8                  50293                     8669                     6989
9                  49877                     8130                     6367
10                 51613                     6888                     5712
11                 56264                     7195                     6879
12                 60915                     6432                     6198
13                 65566                     7850                     6853
14                 65823                     5958                     7025
15                 67288                     6247                     6543
16                 63033                     5674                     7608
17                 62273                     5880                     9600
18                 66130                     5689                    10091
19                 42771                     4821                     7459
20                 46662                     5946                     7310
21                 53050                     6371                     8779

    robos_hechos_formosa  ...  robos_tasa_neuquen  robos_tasa_rio_negro  \
0                   2207  ...           1820.5000            1122.80000
1                   2650  ...           2048.0000            1325.20000
2                   2278  ...           2042.4000            1094.60000
3                   1948  ...           1988.8000             944.79999
4                   1593  ...           1920.6000             862.50000
5                   1748  ...           1720.5000             838.79999
6                   1724  ...           1672.5000            1034.60000
7                   1804  ...           1935.6000            1189.00000
8                   2005  ...           2019.4000            1294.20000
9                   1979  ...           2178.1001            1166.80000
10                  1818  ...           1954.5000            1253.20000
11                  2194  ...           2011.3000            1570.10000
12                  2537  ...           2101.3000            1550.20000
13                  3617  ...           2493.1001            1727.30000
14                  3298  ...           2376.8000            1278.20000
15                  4120  ...           2402.1001            1303.60000
16                  3610  ...           2257.7000            1162.20000
17                  3390  ...           2102.6001            1144.70000
18                  3278  ...           2329.8000            1146.70000
19                  2292  ...           1722.9000             744.50000
20                  2516  ...           1929.6000             870.59998
21                  3125  ...           1970.2000             960.70001

    robos_tasa_salta  robos_tasa_san_juan  robos_tasa_san_luis  \
0          454.79999           1147.50000            662.09998
1          572.29999           1487.20000            808.09998
2          520.00000           1303.30000            955.40002
3          704.79999           1239.10000            831.00000
4         1063.20000           1066.30000            660.29999
5         1063.40000           1064.80000            587.40002
6         1202.60000           1077.30000            689.70001
7         1102.60000           1061.50000            797.09998
8         1096.40000            968.29999            749.09998
9         1094.80000            965.40002            784.79999
10        1172.70000           1200.90000            811.20001
11        1024.90000           1187.50000            909.29999
12        1179.20000           1033.60000            822.20001
13        1524.80000           1057.20000            729.09998
14        1522.50000            956.50000            461.39999
15        1421.90000           1047.40000            506.39999
16        1342.80000           1032.90000            425.39999
17        1342.00000           1069.10000            353.70001
18        1398.80000           1082.20000            455.00000
19        1208.90000            939.00000            380.29999
20        1349.70000            978.50000            440.70001
21        1396.00000           1179.10000            555.40002

    robos_tasa_santa_cruz  robos_tasa_santa_fe  robos_tasa_sgo_estero  \
0               892.59998            972.29999              378.39999
1              1174.40000           1128.00000              498.60001
2              1236.10000           1088.10000              439.50000
3              1057.40000           1063.60000              574.79999
4               957.50000           1235.80000              455.10001
5               893.00000           1160.60000              514.79999
6               858.70001           1205.60000              419.50000
7               926.59998           1253.00000              383.29999
8              1008.80000           1434.30000              379.20001
9              1026.70000           1449.10000              330.29999
10              993.59998           1471.20000              268.89999
11             1065.80000           1552.70000              207.70000
12              983.70001           1569.00000              138.50000
13              864.00000           1482.10000              313.00000
14              801.00000           1527.40000              514.20001
15              883.20001           1476.20000              639.50000
16              807.59998           1275.60000              877.90002
17              798.90002           1392.60000             1012.10000
18              790.40002           1394.70000             1023.50000
19              584.40002           1100.20000              619.20001
20              562.20001           1175.40000              707.20001
21              605.00000           1210.10000              859.09998

    robos_tasa_tierra_fuego  robos_tasa_tucuman
0                 634.20001           510.00000
1                 813.70001           676.90002
2                 768.70001           595.59998
3                 706.59998           587.90002
4                 651.00000           647.70001
5                 676.50000           613.70001
6                 753.20001           604.70001
7                 785.29999           510.20001
8                 899.50000           509.10001
9                 661.50000           477.00000
10                447.89999           548.20001
11                454.10001           627.40002
12                623.00000           625.90002
13                677.00000          1040.10000
14                595.50000          1031.80000
15                581.40002          1094.50000
16                649.59998          1206.20000
17                579.00000          1148.80000
18                543.20001          1199.50000
19                328.10001           965.09998
20                315.10001          1006.40000
21                306.10001          1353.80000

[22 rows x 49 columns]>

In [13]:
df_delitos['robos_hechos_buenos_aires'].unique

<bound method Series.unique of 0     118351
1     153518
2     131978
3      97113
4      64252
5      58863
6      59560
7      77413
8      63145
9      71299
10     88501
11     94059
12     95379
13     99744
14     91761
15     91522
16     92512
17    105185
18    155512
19    115916
20    115029
21    105889
Name: robos_hechos_buenos_aires, dtype: int64>